# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - 'feature-ms-eddiebaeza-mensaje'

pool: 
  ##vmImage: ubuntu-latest
  name: ubuntu
steps:
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'Build and Generate JaCoCo report'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: true
  displayName: 'Build y JaCoCo report'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'mostwanted001'
    projectKey: 'mostwanted001_microservicio-spring'
    projectName: 'microservicio-spring'
  displayName: 'SonarCloud Prepare'
